name: Update Steam Playtime

on:
  workflow_dispatch: 
  schedule:
    - cron: "0 0 * * *"
    
env:
  TZ: Asia/Shanghai
  
jobs:
  build:
    name: Update-Steam-Playtime
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GIST_ID: 6f5c24167c0b5688b54905f2818eef75
      STEAM_API_KEY: ${{ secrets.WEB_API }}
      STEAM_ID: ${{ secrets.ID }}
      UPDATE_OPTION: MARKDOWN
      MARKDOWN_FILE: README.md
      STEAM_OPTION: RECENT

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Check out repo
        uses: actions/checkout@v2

      - name: Clone and run steam-box
        run: |-
          git clone https://github.com/YouEclipse/steam-box.git 
          cd steam-box
          go build -o steam ./cmd/box/main.go
          mv ./steam ../
          cd ..
          rm -rf steam-box/
          
      - name: 'Get current date'
        id: current_date
        run: |
          echo "date=$(date +"%Y-%m-%d_%H-%M-%S")" >> $GITHUB_OUTPUT

      - name: Commit and push
        run: |-
          ./steam
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add README.md
          git commit -m "${{ steps.current_date.outputs.date }} Update Steam Playtime" || exit 0

      - name: 'Push'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
